"""CCF A类会议/期刊的 DBLP key 映射表"""

# 会议：key 以 conf/ 开头
CCF_A_CONFERENCES = {
    # 网络与信息安全
    "ccs": "conf/ccs",
    "eurocrypt": "conf/eurocrypt",
    "sp": "conf/sp",
    "crypto": "conf/crypto",
    "uss": "conf/uss",
    "ndss": "conf/ndss",
    # 软件工程/系统软件/程序设计语言
    "pldi": "conf/pldi",
    "popl": "conf/popl",
    "fse": "conf/fse",
    "sosp": "conf/sosp",
    "oopsla": "conf/oopsla",
    "ase": "conf/ase",
    "icse": "conf/icse",
    "issta": "conf/issta",
    "osdi": "conf/osdi",
    "fm": "conf/fm",
    # 计算机体系结构/并行与分布计算/存储系统
    "ppopp": "conf/ppopp",
    "fast": "conf/fast",
    "dac": "conf/dac",
    "hpca": "conf/hpca",
    "micro": "conf/micro",
    "sc": "conf/sc",
    "asplos": "conf/asplos",
    "isca": "conf/isca",
    "usenix_atc": "conf/usenix",
    "eurosys": "conf/eurosys",
    "hpdc": "conf/hpdc",
    # 数据库/数据挖掘/内容检索
    "sigmod": "conf/sigmod",
    "sigkdd": "conf/kdd",
    "icde": "conf/icde",
    "sigir": "conf/sigir",
    "vldb": "conf/vldb",
    # 计算机科学理论
    "stoc": "conf/stoc",
    "soda": "conf/soda",
    "cav": "conf/cav",
    "focs": "conf/focs",
    "lics": "conf/lics",
    # 计算机图形学与多媒体
    "acmmm": "conf/mm",
    "siggraph": "conf/siggraph",
    "vr": "conf/vr",
    "ieeevis": "conf/visualization",
    # 人工智能
    "aaai": "conf/aaai",
    "neurips": "conf/nips",
    "acl": "conf/acl",
    "cvpr": "conf/cvpr",
    "iccv": "conf/iccv",
    "icml": "conf/icml",
    "iclr": "conf/iclr",
    # 人机交互与普适计算
    "cscw": "conf/cscw",
    "chi": "conf/chi",
    "ubicomp": "conf/huc",
    "uist": "conf/uist",
    # 交叉/综合/新兴
    "www": "conf/www",
    "rtss": "conf/rtss",
    # 计算机网络
    "sigcomm": "conf/sigcomm",
    "mobicom": "conf/mobicom",
    "infocom": "conf/infocom",
    "nsdi": "conf/nsdi",
}

# 期刊：key 以 journals/ 开头
CCF_A_JOURNALS = {
    # 网络与信息安全
    "tdsc": "journals/tdsc",
    "tifs": "journals/tifs",
    "joc": "journals/joc",
    # 软件工程
    "toplas": "journals/toplas",
    "tosem": "journals/tosem",
    "tse": "journals/tse",
    "tsc": "journals/tsc",
    # 体系结构
    "tocs": "journals/tocs",
    "tos": "journals/tos",
    "tcad": "journals/tcad",
    "tc": "journals/tc",
    "tpds": "journals/tpds",
    "taco": "journals/taco",
    # 数据库
    "tods": "journals/tods",
    "tois": "journals/tois",
    "tkde": "journals/tkde",
    "vldbj": "journals/vldb",
    # 理论
    "tit": "journals/tit",
    "iandc": "journals/iandc",
    "siamcomp": "journals/siamcomp",
    # 图形学
    "tog": "journals/tog",
    "tip": "journals/tip",
    "tvcg": "journals/tvcg",
    "tmm": "journals/tmm",
    # AI
    "ai": "journals/ai",
    "tpami": "journals/tpami",
    "ijcv": "journals/ijcv",
    "jmlr": "journals/jmlr",
    # 人机交互
    "tochi": "journals/tochi",
    "ijhcs": "journals/ijhcs",
    # 交叉
    "jacm": "journals/jacm",
    "pieee": "journals/pieee",
    "chinaf": "journals/chinaf",
    "bioinformatics": "journals/bioinformatics",
    # 网络
    "jsac": "journals/jsac",
    "tmc": "journals/tmc",
    "ton": "journals/ton",
}

ALL_CCF_A = {**CCF_A_CONFERENCES, **CCF_A_JOURNALS}
